"""change keys

Revision ID: 0d1c00fe05fa
Revises: 
Create Date: 2022-11-22 00:51:28.409116

"""
from alembic import op
import sqlalchemy as sa
from src.sql_models.types import Varchar

# revision identifiers, used by Alembic.
revision = '0d1c00fe05fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acto-clinico',
    sa.Column('nhc', Varchar(length=8), nullable=True),
    sa.Column('id_actoclinico', Varchar(), nullable=False),
    sa.Column('id_proceso', Varchar(), nullable=True),
    sa.Column('estado', Varchar(length=16), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('ns', Varchar(length=6), nullable=True),
    sa.Column('tipo', Varchar(length=17), nullable=True),
    sa.Column('id_gravedad', sa.SmallInteger(), nullable=True),
    sa.Column('id_motivo_alta', sa.SmallInteger(), nullable=True),
    sa.Column('motivo_alta', Varchar(length=64), nullable=True),
    sa.Column('id_motivo_ingreso', sa.SmallInteger(), nullable=True),
    sa.Column('motivo_ingreso', Varchar(length=64), nullable=True),
    sa.Column('id_motivo_llegada', sa.SmallInteger(), nullable=True),
    sa.Column('motivo_llegada', Varchar(length=64), nullable=True),
    sa.Column('cod_prestacion', Varchar(length=10), nullable=True),
    sa.Column('desc_prestacion', Varchar(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id_actoclinico')
    )
    op.create_index(op.f('ix_acto-clinico_id_actoclinico'), 'acto-clinico', ['id_actoclinico'], unique=True)
    op.create_index(op.f('ix_acto-clinico_id_proceso'), 'acto-clinico', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_acto-clinico_nhc'), 'acto-clinico', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acto-clinico_nhc'), table_name='acto-clinico')
    op.drop_index(op.f('ix_acto-clinico_id_proceso'), table_name='acto-clinico')
    op.drop_index(op.f('ix_acto-clinico_id_actoclinico'), table_name='acto-clinico')
    op.drop_table('acto-clinico')
    # ### end Alembic commands ###
