"""create codificacion

Revision ID: 2819835cc451
Revises: ee9e7a4aabff
Create Date: 2022-11-22 11:58:28.711558

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2819835cc451'
down_revision = 'ee9e7a4aabff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codificacion',
    sa.Column('nhc', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_actoclinico', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('id_proceso', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('id_codificacion', sa.Integer(), nullable=True),
    sa.Column('nivel_codificacion', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('tipo_codificacion', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('secuencia', sa.SmallInteger(), nullable=True),
    sa.Column('fecha_cod', sa.DateTime(), nullable=True),
    sa.Column('hora_cod', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('tipo_acto', mysql.VARCHAR(length=17), nullable=True),
    sa.Column('serv_cod', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('lateralidad', mysql.CHAR(length=1), nullable=True),
    sa.Column('tipo_poa', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('codigo', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('desc_cod', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cod_grupo', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('desc_grupo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_catalogo', mysql.TINYINT(), nullable=True),
    sa.Column('desc_catalogo', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('es_cie10', sa.Boolean(), nullable=True),
    sa.Column('cmbd', sa.Boolean(), nullable=True),
    sa.Column('id_tipo_codigo', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('morfologia', mysql.CHAR(length=2), nullable=True),
    sa.Column('partos', sa.Boolean(), nullable=True),
    sa.Column('ce', sa.Boolean(), nullable=True),
    sa.Column('rn_patologico', sa.Boolean(), nullable=True),
    sa.Column('abortos', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_actoclinico')
    )
    op.create_index(op.f('ix_codificacion_id_actoclinico'), 'codificacion', ['id_actoclinico'], unique=True)
    op.create_index(op.f('ix_codificacion_id_proceso'), 'codificacion', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_codificacion_nhc'), 'codificacion', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codificacion_nhc'), table_name='codificacion')
    op.drop_index(op.f('ix_codificacion_id_proceso'), table_name='codificacion')
    op.drop_index(op.f('ix_codificacion_id_actoclinico'), table_name='codificacion')
    op.drop_table('codificacion')
    # ### end Alembic commands ###
