"""change keys

Revision ID: 3a9e3ce161f4
Revises: 7a9397970494
Create Date: 2022-11-22 09:44:41.690904

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '3a9e3ce161f4'
down_revision = '7a9397970494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
