"""create proceso

Revision ID: 419747f673f4
Revises: 5b69497185da
Create Date: 2022-11-22 12:23:46.679084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '419747f673f4'
down_revision = '5b69497185da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso',
    sa.Column('nhc', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_proceso', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('desc_proceso', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('servicio_proceso', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('fecha_ini_proceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_proceso', sa.DateTime(), nullable=True),
    sa.Column('fusionado_a', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('id_estado_proceso', mysql.TINYINT(), nullable=True),
    sa.Column('estado_proceso', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('id_proceso_padre', sa.Integer(), nullable=True),
    sa.Column('id_tipo_proceso', sa.Integer(), nullable=True),
    sa.Column('tipo_proceso', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_ubicacion_proce', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('restringido', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_proceso')
    )
    op.create_index(op.f('ix_proceso_id_proceso'), 'proceso', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_proceso_nhc'), 'proceso', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proceso_nhc'), table_name='proceso')
    op.drop_index(op.f('ix_proceso_id_proceso'), table_name='proceso')
    op.drop_table('proceso')
    # ### end Alembic commands ###
