"""create paciente

Revision ID: 5b69497185da
Revises: 80eafae0e149
Create Date: 2022-11-22 12:16:42.152564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b69497185da'
down_revision = '80eafae0e149'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('nhc', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('area_salud', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('centro_ref', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('comun_aut', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('foreign_patient', sa.Boolean(), nullable=True),
    sa.Column('sex', mysql.CHAR(length=1), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('pendiente_exitus', sa.Boolean(), nullable=True),
    sa.Column('death_indicator', sa.Boolean(), nullable=True),
    sa.Column('codigo_ciudadano', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('id_tipo_ciudadano', sa.SmallInteger(), nullable=True),
    sa.Column('tipo_paciente', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_pendiente_exitus', sa.DateTime(), nullable=True),
    sa.Column('fecha_exitus', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nhc')
    )
    op.create_index(op.f('ix_paciente_nhc'), 'paciente', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paciente_nhc'), table_name='paciente')
    op.drop_table('paciente')
    # ### end Alembic commands ###
