"""create formularios

Revision ID: 65c5db089326
Revises: 2819835cc451
Create Date: 2022-11-22 12:05:38.199003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65c5db089326'
down_revision = '2819835cc451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formularios',
    sa.Column('nhc', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_actoclinico', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('id_proceso', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('id_formulario', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('id_toma', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('formulario', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fecha_toma', sa.DateTime(), nullable=True),
    sa.Column('cod_indicador', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('indicador', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valor', mysql.TEXT(), nullable=True),
    sa.Column('fecha_desde', sa.DateTime(), nullable=True),
    sa.Column('fecha_hasta', sa.DateTime(), nullable=True),
    sa.Column('fecha_desde_1', sa.DateTime(), nullable=True),
    sa.Column('fecha_hasta_1', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_actoclinico')
    )
    op.create_index(op.f('ix_formularios_id_actoclinico'), 'formularios', ['id_actoclinico'], unique=True)
    op.create_index(op.f('ix_formularios_id_formulario'), 'formularios', ['id_formulario'], unique=False)
    op.create_index(op.f('ix_formularios_id_proceso'), 'formularios', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_formularios_nhc'), 'formularios', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formularios_nhc'), table_name='formularios')
    op.drop_index(op.f('ix_formularios_id_proceso'), table_name='formularios')
    op.drop_index(op.f('ix_formularios_id_formulario'), table_name='formularios')
    op.drop_index(op.f('ix_formularios_id_actoclinico'), table_name='formularios')
    op.drop_table('formularios')
    # ### end Alembic commands ###
