"""change keys

Revision ID: 7a9397970494
Revises: f093077c62e0
Create Date: 2022-11-22 01:01:47.725632

"""
from alembic import op
import sqlalchemy as sa
from src.models.types import Varchar
dir()

# revision identifiers, used by Alembic.
revision = '7a9397970494'
down_revision = 'f093077c62e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acto-clinico', sa.Column('estado', Varchar(length=16), nullable=True))
    op.add_column('acto-clinico', sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
    op.add_column('acto-clinico', sa.Column('fecha_fin', sa.DateTime(), nullable=True))
    op.add_column('acto-clinico', sa.Column('ns', Varchar(length=6), nullable=True))
    op.add_column('acto-clinico', sa.Column('tipo', Varchar(length=17), nullable=True))
    op.add_column('acto-clinico', sa.Column('id_gravedad', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acto-clinico', 'id_gravedad')
    op.drop_column('acto-clinico', 'tipo')
    op.drop_column('acto-clinico', 'ns')
    op.drop_column('acto-clinico', 'fecha_fin')
    op.drop_column('acto-clinico', 'fecha_inicio')
    op.drop_column('acto-clinico', 'estado')
    # ### end Alembic commands ###
