"""create notas

Revision ID: 80eafae0e149
Revises: 8fa9893fb4b5
Create Date: 2022-11-22 12:10:31.820782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80eafae0e149'
down_revision = '8fa9893fb4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('nhc', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_actoclinico', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('id_proceso', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('contenido', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_actoclinico')
    )
    op.create_index(op.f('ix_notas_id_actoclinico'), 'notas', ['id_actoclinico'], unique=True)
    op.create_index(op.f('ix_notas_id_proceso'), 'notas', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_notas_nhc'), 'notas', ['nhc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_nhc'), table_name='notas')
    op.drop_index(op.f('ix_notas_id_proceso'), table_name='notas')
    op.drop_index(op.f('ix_notas_id_actoclinico'), table_name='notas')
    op.drop_table('notas')
    # ### end Alembic commands ###
