"""change keys

Revision ID: 868203f961f5
Revises: 0d1c00fe05fa
Create Date: 2022-11-22 00:55:01.348769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868203f961f5'
down_revision = '0d1c00fe05fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
