"""create resultados-peticiones again

Revision ID: aee6276e9d35
Revises: b0b459717b83
Create Date: 2022-11-22 12:32:54.731323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee6276e9d35'
down_revision = 'b0b459717b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
