"""create resultados-peticiones

Revision ID: b0b459717b83
Revises: 9baa4d1289c6
Create Date: 2022-11-22 12:32:31.985515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b459717b83'
down_revision = '9baa4d1289c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
