"""change keys

Revision ID: b0db701908c7
Revises: 868203f961f5
Create Date: 2022-11-22 00:55:47.319578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0db701908c7'
down_revision = '868203f961f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acto-clinico', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acto-clinico', sa.Column('estado', mysql.VARCHAR(length=16), nullable=True))
    # ### end Alembic commands ###
