"""create traslados

Revision ID: b19bcd020c58
Revises: 1830ae47d947
Create Date: 2022-11-22 12:36:53.373567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19bcd020c58'
down_revision = '1830ae47d947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
