"""create traslados

Revision ID: d66c4eca021e
Revises: 6a75aae123d4
Create Date: 2022-11-22 12:52:15.035429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66c4eca021e'
down_revision = '6a75aae123d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
