"""hola

Revision ID: ee9e7a4aabff
Revises: 712f0d8b5b23
Create Date: 2022-11-22 11:37:52.455033

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'ee9e7a4aabff'
down_revision = '712f0d8b5b23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
