"""change keys

Revision ID: f093077c62e0
Revises: 7d84d2d3f657
Create Date: 2022-11-22 00:58:37.532412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f093077c62e0'
down_revision = '7d84d2d3f657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
